<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bahan_asets extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bahan_asets_model');
    }

    public function truncate_all()
    {
        $res = $this->db->query("TRUNCATE bahan_asets;");
        if($res){
            $this->session->set_flashdata('truncated', 'Berhasil membersihkan data Bahan Aset');
        }
        redirect("Asets/set_truncate");
    }

    public function index()
    {
        $bahan_asets = $this->Bahan_asets_model->get_all();

        $data = array(
            'bahan_data' => $bahan_asets,
            'judul' => "Bahan Asets",
            'breadcrumb' => array("Data Lainnya", "Bahan Asets"),
            'bootstrap' => array("assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css", "assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css"),
            'script' => TRUE,
            'konten' => "bahan_asets/bahan_asets_list",
        );
        $this->load->view('container', $data);
    }
    
    public function create_action() 
    {
        $data = array(
            'bahan' => $this->input->post('bahan',TRUE),
            'keterangan' => $this->input->post('keterangan',TRUE),
        );

        $this->Bahan_asets_model->insert($data);
        $this->session->set_flashdata('message', 'Bahan Assets berhasil ditambahkan');
        redirect('Bahan_asets');
    }
    
    public function update_action() 
    {
        $data = array(
            'bahan' => $this->input->post('bahan',TRUE),
            'keterangan' => $this->input->post('keterangan',TRUE),
        );

        $this->Bahan_asets_model->update($this->input->post('id', TRUE), $data);
        $this->session->set_flashdata('message', 'Bahan Assets berhasil ditambahkan');
        redirect('Bahan_asets');
    }
    
    public function delete($id) 
    {
        $row = $this->Bahan_asets_model->get_by_id($id);

        if ($row) {
            $this->Bahan_asets_model->delete($id);
            $this->session->set_flashdata('message', 'Bahan Assets berhasil dihapus');
            redirect('Bahan_asets');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect('Bahan_asets');
        }
    }

}

/* End of file Bahan_asets.php */
/* Location: ./application/controllers/Bahan_asets.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-05 10:55:33 */
/* http://harviacode.com */