<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tipe_asets extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipe_asets_model');
    }

    public function truncate_all()
    {
        $res = $this->db->query("TRUNCATE tipe_asets;");
        if($res){
            $this->session->set_flashdata('truncated', 'Berhasil membersihkan data Tipe Aset');
        }
        redirect("Asets/set_truncate");
    }

    public function index()
    {
        $tipe_asets = $this->Tipe_asets_model->get_all();

        $data = array(
            'tipe_data' => $tipe_asets,
            'judul' => "Tipe Asets",
            'breadcrumb' => array("Data Lainnya", "Tipe Asets"),
            'bootstrap' => array("assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css", "assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css"),
            'script' => TRUE,
            'konten' => "tipe_asets/tipe_asets_list",
        );
        $this->load->view('container', $data);
    }
    
    public function create_action() 
    {
        $data = array(
            'tipe' => strtoupper($this->input->post('tipe',TRUE)),
            'keterangan' => $this->input->post('keterangan',TRUE),
        );

        $this->Tipe_asets_model->insert($data);
        $this->session->set_flashdata('message', 'Tipe Assets berhasil ditambahkan');
        redirect('Tipe_asets');
    }
    
    public function update_action() 
    {
        $data = array(
            'tipe' => strtoupper($this->input->post('tipe',TRUE)),
            'keterangan' => $this->input->post('keterangan',TRUE),
        );

        $this->Tipe_asets_model->update($this->input->post('id', TRUE), $data);
        $this->session->set_flashdata('message', 'Tipe Assets berhasil diubah');
        redirect('Tipe_asets');
    }
    
    public function delete($id) 
    {
        $row = $this->Tipe_asets_model->get_by_id($id);

        if ($row) {
            $this->Tipe_asets_model->delete($id);
            $this->session->set_flashdata('message', 'Tipe Assets berhasil dihapus');
            redirect('Tipe_asets');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect('Tipe_asets');
        }
    }

}

/* End of file Tipe_asets.php */
/* Location: ./application/controllers/Tipe_asets.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-05 10:55:35 */
/* http://harviacode.com */